# Generated by Django 4.1.2 on 2022-10-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellidoP', models.CharField(max_length=200)),
                ('apellidoM', models.CharField(max_length=200)),
                ('fechaNacimiento', models.DateField()),
                ('correoElectronico', models.CharField(max_length=200)),
                ('contraseña', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('calle', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=200)),
                ('colonia', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=200)),
                ('codigoPostal', models.CharField(max_length=200)),
            ],
        ),
    ]
